### PR TITLE
Create it_it.json

### PR DESCRIPTION
**Pull request by Zano1999**

### CODE REVIEW

**Comment by BarionLP** [comment]
thank you for translating! In the last commit I added one more advancement would be really nice if you could translate it too

**Comment by Zano1999** [comment]
Done

**Comment by BarionLP** [comment]
perfect

**Review by BarionLP — APPROVED** [review]

**Comment by BarionLP** [comment]
if you want to continue translating you can now use [OneSky](https://ametrin-studios-mods.oneskyapp.com/collaboration/project?id=187381)

**Pull request merged**
